

/*MailAntet*/
INSERT INTO [EmailLetterhead] ([Id],[Description],[Content],UniqueId) VALUES (Next Value For dbo.sqEmailLetterhead,N'Genel',N'<div style="display:inline-block;border:1px solid gainsboro;"><div style="border-bottom:1px solid gainsboro;"><a href="https://qq.com"><img src="https://qq.com/img/mail/header_2020_05_19.png" alt="" width="925" /></a></div><div style="border-bottom:1px solid gainsboro;"><div style="padding:30px 15px;"><p>[#AntetContent#]</p></div></div><div><a href="https://qq.com"><img src="https://qq.com/img/mail/footer_2020_05_19.png" alt="" width="925" /></a></div></div>', newid());

/*MailSablon*/
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (101, 1, N'Şifre bildirimi', N'', N'Şifre bildirimi.', N'<p><span style="font-size:xx-large;">ŞİFRE BİLDİRİM</span><br /><span style="font-size:x-small;"></span><span style="font-size:small;"></span><span style="font-size:medium;"></span></p><p style="text-align:justify;"><span style="font-size:large;">Yeni şifreniz oluşturulmuştur.<br /></span></p><table style="width:810px;"><tbody><tr><td style="width:155px;"><span style="font-size:large;"><strong>Kullanıcı Adı</strong></span></td><td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#Kullanici_Ad#]</span></td></tr><tr><td style="width:155px;"><span style="font-size:large;"><strong>Şifre</strong></span></td><td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#Kullanici_Sifre#]</span></td></tr></tbody></table><p><span style="font-size:large;"><em><br />Belirli zaman aralıklarıyla şifrenizi değiştirmeyi unutmayınız.</em></span></p><p><em><span style="font-size:large;">&nbsp;</span></em></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (102, 1, N'Üyelik onay bildirimi', N'', N'Üyelik onay bildirimi.', N'<p><br /><span style="font-size:large;"></span></p><p style="text-align:justify;"><span style="font-size:large;">Sayın [#AdSoyad#], </span></p><p style="text-align:justify;"><span style="font-size:large;">Üyelik talebiniz alınmıştır, üyeliğinizin aktif olması için aşağıdaki link den onaylamanız gerekmektedir.</span></p><p>&nbsp;</p><p><a href="[#OnayLinkValue#]" target="_blank"><span>[#OnayLinkText#]</span></a></p><p>&nbsp;</p><p><span style="font-size:large;"><em>Bu talebi yapan eğer siz değil iseniz, dikkate almayınız.</em></span></p><p><span style="font-size:large;"><em></em> </span></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (103, 1, N'Şifre sıfırlama bildirimi', N'', N'Şifre sıfırlama bildirimi.', N'<p><br /><span style="font-size:large;"></span></p><p style="text-align:justify;"><span style="font-size:large;">Sayın [#AdSoyad#], </span></p><p style="text-align:justify;"><span style="font-size:large;">Şifre yenileme talebiniz alınmıştır,  aşağıdaki link den yeni şifrenizi oluşturabilirsiniz.</span></p><p>&nbsp;</p><p><a href="[#LinkValue#]" target="_blank"><span>[#LinkText#]</span></a></p><p>&nbsp;</p><p><span style="font-size:large;"><em>Bu talebi yapan eğer siz değil iseniz, dikkate almayınız.</em></span></p><p><span style="font-size:large;"><em></em> </span></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (104, 1, N'Job hata bildirimi', N'', N'Job hata bildirimi.', N'<p><br /><span style="font-size:large;"></span></p><p style="text-align:justify;"><span style="font-size:large;"><strong>Sayın İlgili, </strong></span></p><p style="text-align:justify;"><span style="font-size:large;">Zamanlı çalışan görevler bölümünde bir hata meydana gelmiştir, detayları aşağıdadır.</span></p><p style="text-align:justify;"><span style="font-size:large;">&nbsp;</span></p><p style="text-align:justify;"><span style="text-align:justify;font-size:large;">İşlem Zamanı : </span><span style="text-align:justify;">[#IslemZamani#]</span></p><p style="text-align:justify;"><span style="font-size:large;">İşlem Adı : </span>[#IslemAdi#]<br /></p><div><span style="font-size:large;text-align:justify;">Açıklama : </span><span style="text-align:justify;">[#Aciklama#]</span><span style="font-size:large;"><br /></span></div><p style="text-align:justify;"><br /><span style="font-size:large;"><em></em></span></p><p><span style="font-size:large;"><em></em> </span></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (105, 1, N'Üye ödeme bildirimi', N'', N'Üye ödeme bildirimi.', N'<p><span style="font-size:xx-large;">ÖDEME BİLDİRİM</span><br />  <span style="font-size:x-small;"></span><span style="font-size:small;"></span><span style="font-size:medium;"></span></p>  <p style="text-align:justify;">    Sn.<span style="font-size:large;">[#AdSoyad#]<span />    <span style="font-size:large;"> ödemeniz alınmıştır.<br /></span>  </p>  <table style="width:810px;"><tbody><tr><td style="width:155px;"><span style="font-size:large;"><strong>İşlem Tarihi</strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#IslemZamani#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Yatırım Tutarı </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#YatirimTutari#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Bakiye </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#Bakiye#]</span></td>  </tr>  </tbody></table>  <p><span style="font-size:large;"><em><br />  Smart Ankara uygulamasını kullandığınız için teşekkür ederiz.</em></span></p>  <p><em><span style="font-size:large;">&nbsp;</span></em></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (106, 1, N'Üye sürüş bildirimi', N'', N'Üye sürüş bildirimi.', N'<p><span style="font-size:xx-large;">SÜRÜŞ BİLDİRİM</span><br />  <span style="font-size:x-small;"></span><span style="font-size:small;"></span><span style="font-size:medium;"></span></p>  <p style="text-align:justify;">    Sn.<span style="font-size:large;">[#AdSoyad#]<span />    <span style="font-size:large;"> sürüş bilgileriniz;<br /></span>  </p>  <table style="width:810px;"><tbody><tr><td style="width:155px;"><span style="font-size:large;"><strong>Araç Bilgisi</strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#AracAd#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Başlangıç Tarih / Zamanı </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#BaslangicTarih#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Bitiş Tarih / Zamanı </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#BitisTarih#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Toplam Süre </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#ToplamSure#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Tutar </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#Tutar#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Bakiye </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#Bakiye#]</span></td>  </tr>  </tbody></table>  <p><span style="font-size:large;"><em><br />  Smart Ankara uygulamasını kullandığınız için teşekkür ederiz.</em></span></p>  <p><em><span style="font-size:large;">&nbsp;</span></em></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (107, 1, N'Araç Sarj Uyarısı', N'', N'Sistem araç şarj uyarısıdır.', N'<p><span style="font-size:xx-large;">ARAÇ ŞARJ UYARISI</span><br />  <span style="font-size:x-small;"></span><span style="font-size:small;"></span><span style="font-size:medium;"></span></p>  <p style="text-align:justify;">    <span style="font-size:large;">[#AracAd#]<span />    <span style="font-size:large;"> isimli araç şarj uyarısı vermektedir.<br /></span>  </p>  <table style="width:810px;"><tbody>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>İşlem Zamanı </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#IslemZamani#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>IMEI No</strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#ImeiNo#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Araç Bilgisi</strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#AracAd#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Kullanım Durumu </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#KullanimDurumu#]</span></td>  </tr>  <tr><td style="width:155px;"><span style="font-size:large;"><strong>Şarj Oranı </strong></span></td>  <td style="width:653px;"><span style="font-size:large;"><strong>:</strong> [#SarjOrani#]</span></td>  </tr>  </tbody></table>  <p><span style="font-size:large;"><em><br />  Smart Ankara sistem bildirimi.</em></span></p>  <p><em><span style="font-size:large;">&nbsp;</span></em></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (108, 1, N'Araç Yasaklı Bölge Uyarısı', N'', N'Sistem yasaklı bölgeye giriş yapan araç uyarısıdır.', N'<p><span style="font-size:xx-large;">ARAÇ YASAKLI BÖLGE UYARISI</span><br />  <span style="font-size:x-small;"></span><span style="font-size:small;"></span><span style="font-size:medium;"></span></p>  <p style="text-align:justify;">    <span style="font-size:large;">[#IslemZamani#] tarihinde [#ImeiNo#] Imei numarasına sahip [#AracAd#] isimli araç, [#YasakliBolgeAd#] yasaklı bölgesine giriş yapmıştır.<br /></span>  </p>  <p><span style="font-size:large;"><em><br />  Smart Ankara sistem bildirimi.</em></span></p>  <p><em><span style="font-size:large;">&nbsp;</span></em></p>', newid());
INSERT INTO [EmailTemplate] ([Id],[EmailLetterheadId],[Name],[EmailCc],[EmailSubject],[EmailContent],UniqueId) VALUES (109, 1, N'Üye Araç Yasaklı Bölge Uyarısı', N'', N'Üye Araç Yasaklı Bölge Uyarısı', N'<p><span style="font-size:xx-large;">ARAÇ YASAKLI BÖLGE UYARISI</span><br />  <span style="font-size:x-small;"></span><span style="font-size:small;"></span><span style="font-size:medium;"></span></p>  <p style="text-align:justify;">    <span style="font-size:large;">Sn. [#AdSoyad#], <br/> [#IslemZamani#] tarihinde  [#AracAd#] isimli araç, [#YasakliBolgeAd#] yasaklı bölgesine giriş yaptınız. <br /></span>  </p>  <p><span style="font-size:large;"><em><br />  Smart Ankara sistem bildirimi.</em></span></p>  <p><em><span style="font-size:large;">&nbsp;</span></em></p>', newid());


/*Araç Özellikleri*/
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'iot_sw', 'IOT Software Version');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'iot_hw', 'IOT Hardware Version');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'ecu_fw', 'ECU Firmware Version');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'ecu_hw', 'ECU Hardware Version');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'ble_fw', 'Bluetooth Firmware Version');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'blk_fw', 'Battery Lock Firmware Version');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'hlk_fw', 'Hub Lock Firmware Version');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'iccid', 'ICCID');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'vehicle_serial', 'Serial Number');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'iot_serial', 'IoT Serial Number');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'ecu_serial', 'ECU Serial Number');
INSERT INTO AracOzellik (Id, UniqueId, Durum, Ad, Aciklama) VALUES(Next Value For dbo.sqAracOzellik, newid(), 1, 'ble_mac', 'Bluetooth MAC Address');